import { PAGE_SCHEMA_VERSION, type PageDocument, type SectionStyle } from './pageSchema';

const navySection = (padding: SectionStyle['paddingTop'] = '2xl'): SectionStyle => ({
  background: { kind: 'theme', token: 'primary' },
  paddingTop: padding,
  paddingBottom: padding,
  contentWidth: 'wide',
  textAlign: 'start',
  textColor: { kind: 'theme', token: 'text' },
  accentColor: { kind: 'theme', token: 'accent' },
  headingFamily: 'heading',
  headingScale: 'xl',
  headingWeight: 'bold',
});

/**
 * Version-one data representation of the current homepage. It is seeded into
 * D1 by migration 0002 but is not consumed by App.tsx until Phase 2.
 */
export const INITIAL_HOMEPAGE_DOCUMENT: PageDocument = {
  schemaVersion: PAGE_SCHEMA_VERSION,
  id: 'homepage',
  slug: 'home',
  title: { en: 'LAHAB Homepage', ar: 'الصفحة الرئيسية للهب' },
  settings: {
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar'],
    defaultTheme: 'navy',
  },
  sections: [
    {
      id: 'home-hero',
      type: 'hero',
      visible: true,
      style: {
        ...navySection('2xl'),
        background: {
          kind: 'image',
          asset: { assetId: 'asset-hero-watercolor' },
          position: 'center',
          fit: 'cover',
          overlay: { kind: 'theme', token: 'primary' },
          overlayOpacity: 0.68,
        },
        contentWidth: 'full',
      },
      responsive: { mobile: { paddingTop: 'xl', paddingBottom: 'xl' } },
      content: {
        badge: { en: 'LIMITED ARCHIVE // DROP 01', ar: 'إصدار أرشيفي حصري // المجموعة الأولى' },
        tagline: { en: 'STREETWEAR FORGED IN HERITAGE', ar: 'أزياء الشارع المصهورة في عبق الأصالة' },
        subTagline: {
          en: 'Architectural cuts rooted in calligraphic discipline, nocturnal palettes, and raw street aesthetics. Crafted for those who move in quiet conviction.',
          ar: 'قوالب معمارية مستوحاة من طاقة الخط العربي، ألوان الليل العميقة، وثقافة الشارع المعاصرة. صُممت لمن يتحركون بيقين وهدوء.',
        },
        aestheticTag: { en: 'NIGHT & FIRE AESTHETIC', ar: 'جمالية الليل والنار' },
        fabricTag: { en: 'Heavyweight 520 GSM French Terry & Combed Cotton', ar: 'قطن فرينش تيري ثقيل 520 جرام وقطن ممشط فاخر' },
        editionLabel: { en: 'EDITION', ar: 'الإصدار' },
        editionValue: { en: 'FIRST RUN / 200 PIECES', ar: 'الدفعة الأولى / 200 قطعة' },
        shippingLabel: { en: 'SHIPMENT', ar: 'الشحن' },
        shippingValue: { en: 'WORLDWIDE EXPRESS', ar: 'شحن سريع لجميع أنحاء العالم' },
        scrollPrompt: { en: 'SCROLL TO EXPLORE', ar: 'اسحب لاستكشاف المجموعة' },
        backgroundImage: { assetId: 'asset-hero-watercolor' },
        actions: [
          { id: 'hero-shop-action', label: { en: 'SHOP DROP 01', ar: 'تسوق الإصدار الأول' }, action: { type: 'scrollToSection', sectionId: 'home-products' }, variant: 'primary' },
          { id: 'hero-story-action', label: { en: 'DISCOVER CONCEPT', ar: 'اكتشف المفهوم' }, action: { type: 'scrollToSection', sectionId: 'home-brand-story' }, variant: 'secondary' },
        ],
      },
    },
    {
      id: 'home-calligraphic-banner',
      type: 'calligraphicBanner',
      visible: true,
      style: { ...navySection('lg'), background: { kind: 'theme', token: 'surface' }, contentWidth: 'full', textAlign: 'center' },
      content: {
        showWordmark: true,
        items: [
          { id: 'banner-streetwear', text: { en: 'CONTEMPORARY STREETWEAR', ar: 'أزياء الشارع المعاصرة' }, emphasis: 'accent' },
          { id: 'banner-tagline', text: { en: 'FIRE FORGED IN ARCHITECTURAL FORM', ar: 'طاقة اللهب في قوالب معمارية متقنة' }, emphasis: 'accent' },
          { id: 'banner-origin', text: { en: 'LIMITED FIRST EDITION', ar: 'إصدار أول محدود' }, emphasis: 'muted' },
        ],
      },
    },
    {
      id: 'home-brand-story',
      type: 'brandStory',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: '01 // CONCEPT & HERITAGE', ar: '01 // المفهوم والأصالة' },
        headline: { en: 'THE STREET MEETS CENTURIES OF CALLIGRAPHIC DISCIPLINE.', ar: 'حين يلتقي نبض الشارع بقرون من انضباط فن الخط.' },
        body: {
          en: 'LAHAB was born from a singular conviction: heritage is not a museum artifact—it is an untamed, kinetic current alive in the night streets. We fuse the mathematical geometry of classical script and arabesque line discipline into drop-shoulder, heavyweight streetwear.',
          ar: 'ولدت علامة لَهَب من قناعة راسخة: الثقافة والأصالة ليست أثرًا في متحف، بل تيار جامح ينبض بالحياة في شوارع الليل. نمزج الهندسة الرياضية للخط الكلاسيكي وزخارف الأرابيسك مع قصات أزياء الشارع الثقيلة والواسعة.',
        },
        bodyMobile: { en: 'Heritage isn’t a museum piece — it’s a living current in the night streets, fused into heavyweight drop-shoulder streetwear.', ar: 'الأصالة مش أثر في متحف، هي نبض حي في شوارع الليل — بندمجها في قصات أزياء شارع ثقيلة وعريضة.' },
        visualLabel: { en: 'HERITAGE ARCHITECTURAL CUTS', ar: 'HERITAGE ARCHITECTURAL CUTS' },
        materialTags: [{ en: '520 GSM FLEECE', ar: '520 GSM FLEECE' }, { en: 'GIZA 86 COTTON', ar: 'GIZA 86 COTTON' }],
        features: [
          { id: 'story-silhouettes', title: { en: 'NOVEL SILHOUETTES', ar: 'قصات معمارية مبتكرة' }, description: { en: 'Boxy, drop-shoulder forms engineered with dense fabric drape.', ar: 'تصاميم عريضة بأكتاف ساقطة تمنح القماش ثقلًا وانسيابية فريدة.' } },
          { id: 'story-embroidery', title: { en: 'TACTILE EMBROIDERY', ar: 'تطريز ملموس وعالي الكثافة' }, description: { en: 'Matte gold high-density threadwork that endures relentless wear.', ar: 'خيوط ذهبية مطفية متينة تصمد أمام أصعب ظروف الارتداء اليومي.' } },
          { id: 'story-flame', title: { en: 'LIVING FLAME FORM', ar: 'طاقة خطية متدفقة' }, description: { en: 'Fluid calligraphic energy translated into modern silhouette lines.', ar: 'تتحول حركة الحروف التراثية إلى خطوط ظلية معاصرة مفعمة بالحيوية.' } },
        ],
      },
    },
    {
      id: 'home-editorial',
      type: 'editorialLookbook',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: 'ARCHITECTURAL PROFILE // TEXTILE DISCIPLINE', ar: 'القالب المعماري // انضباط النسيج' },
        title: { en: 'DENSE FABRIC DRAPE. PERMANENT EMBROIDERY.', ar: 'ثقل نسيجي استثنائي. تطريز ذهبي دائم.' },
        subtitle: { en: 'Custom-milled heavyweight combed cotton and French terry. Deep nocturnal navy reactive dye with abrasion-resistant matte gold accents.', ar: 'قطن ممشط فاخر وفرينش تيري بوزن ثقيل خاص. صباغة كحلية ليلية مقاومة للتلاشي مع تفاصيل ذهبية مطفية عالية التحمل.' },
        cards: [
          { id: 'editorial-front', title: { en: 'FRONT ARCHITECTURE // HOODIE', ar: 'هودي الشارع المعماري // الواجهة' }, description: { en: 'Boxy drop-shoulder cut with dense drape, reinforced double hood collar, and high-density matte gold chest embroidery.', ar: 'قصة بأكتاف ساقطة واسعة تضمن ثبات وانسيابية القماش، وتطريز ذهبي مطفي عالي الدقة على الصدر.' }, image: { assetId: 'asset-editorial-streetwear' }, action: { id: 'editorial-size-action', label: { en: 'VIEW SIZE MATRIX', ar: 'جدول المقاسات الكامل' }, action: { type: 'openSizeGuide' }, variant: 'secondary' } },
          { id: 'editorial-back', title: { en: 'FLAME CALLIGRAPHY // BACK', ar: 'طباعة حروف اللهب // الظهر' }, description: { en: 'Monumental arch back print honoring fire calligraphic dynamism, framed by ultra-durable French Terry ribs.', ar: 'طباعة أرشيفية عريضة بحروف لَهَب تعكس طاقة النار، محاطة بحواف متينة ونسيج صوف فرينش تيري فائق النعومة والمتانة.' }, image: { assetId: 'asset-editorial-streetwear' }, action: { id: 'editorial-products-action', label: { en: 'EXPLORE PIECES', ar: 'استعراض القطع' }, action: { type: 'scrollToSection', sectionId: 'home-products' }, variant: 'primary' } },
        ],
      },
    },
    {
      id: 'home-products',
      type: 'productShowcase',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: 'DROP 01 // FIRST EDITION', ar: 'المجموعة الأولى // الإصدار الحصري' },
        title: { en: 'THE ESSENTIAL PIECES', ar: 'القطع الأساسية' },
        limitedUnits: { en: 'Only 100 units per piece released in Drop 01', ar: '100 قطعة فقط مخصصة لكل تصميم في هذا الإصدار' },
        assuranceTitle: { en: 'GARMENT ASSURANCE & MATERIAL STANDARD', ar: 'ضمان الجودة والمعايير النسيجية' },
        assuranceDescription: { en: 'Custom-milled heavyweight cotton & fleece. Color-fast deep navy reactive dye. Embroideries use high-tensile matte gold thread.', ar: 'قطن وصوف فرينش تيري مخصص فائق الكثافة. صباغة تفاعلية ثابتة. تطريز بخيوط ذهبية مطفية عالية الشد.' },
        source: { kind: 'allProducts' },
      },
    },
    {
      id: 'home-garment-viewer',
      type: 'garmentViewer',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: '360° INTERACTIVE GARMENT STUDIO', ar: 'دراسة القوام بزاوية 360 درجة' },
        title: { en: 'Real 3D Garment Studio', ar: 'مجسم الهودي الحقيقي 3D' },
        description: { en: 'Persistent repository 3D asset featuring the authentic 520 GSM boxy drop-shoulder cut, with live interactive 360° orbit controls and PBR studio lighting.', ar: 'مجسم ثلاثي الأبعاد حقيقي مدمج لقصة الهودي البوكسي 520 جرام، مع إمكانية فحص تفاصيل النسيج والتدوير بزاوية 360 درجة بحرية.' },
        productSource: { kind: 'firstAvailableProduct' },
        model: { assetId: 'asset-model-hoodie-obj', format: 'obj', scale: [1, 1, 1], position: [0, 0, 0], rotation: [0, 0, 0], cameraPosition: [0, 0, 5], autoRotate: true, autoRotateSpeed: 0.35, backgroundColor: '#0A1422', lightingPreset: 'studio', materialColor: '#0D1929' },
        allowManualOrbit: true,
        showFallbackMannequin: true,
      },
    },
    {
      id: 'home-product-reviews',
      type: 'productReviews',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: 'CLIENT REVIEWS & FIT GALLERY', ar: 'آراء العملاء وصور المقتنين' },
        title: { en: 'REVIEWS FROM OUR COLLECTORS', ar: 'التقييمات وصور الإطلالات' },
        description: { en: 'Authentic reviews and real fit photos from verified collectors across Cairo, Dubai, and Riyadh highlighting the 520 GSM drape and gold diacritic embroidery.', ar: 'شهادات حقيقية وصور إطلالات من مقتني الإصدار الأول في القاهرة، الإسكندرية، الرياض، ودبي حول وزن نسيج 520 جرام وتطريز خيوط الذهب وقصة الأكتاف.' },
        source: { kind: 'allProductReviews' },
        allowSubmissions: true,
        showFilters: true,
      },
    },
    {
      id: 'home-street-style',
      type: 'streetStyleLookbook',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: 'SEEN IN LΛHΛB // ARCHIVAL STREET-STYLE', ar: 'مجتمع لَهَب // SEEN IN LAHAB' },
        title: { en: 'Community Lookbook', ar: 'أناقة الشارع وتنسيق القطع' },
        items: [
          { id: 'look-cairo-downtown', image: { assetId: 'asset-editorial-streetwear' }, location: { en: 'Downtown Cairo / Kodak Pass', ar: 'وسط البلد / ممر كوداك التاريخي' }, modelName: { en: 'Omar K.', ar: 'عمر ك.' }, productName: { en: 'Drop 01 Heavyweight Hoodie (520 GSM)', ar: 'هودي الإصدار الأول فائق الثقل (520 GSM)' }, stylingNotes: { en: 'Paired with wide-leg raw Japanese denim, structured leather boots, and minimal gold band.', ar: 'تنسيق مع بنطال دنيم ياباني عريض وأحذية جلدية متينة وخاتم ذهبي كلاسيكي.' }, sizeWorn: 'XL', productId: 'hoodie-01', region: 'cairo', visible: true },
          { id: 'look-cairo-zamalek', image: { assetId: 'asset-editorial-streetwear' }, location: { en: 'Zamalek Nile Terrace', ar: 'شرفة الزمالك المطلة على النيل' }, modelName: { en: 'Nour E.', ar: 'نور ع.' }, productName: { en: 'Drop 01 Heavyweight Hoodie (520 GSM)', ar: 'هودي الإصدار الأول فائق الثقل (520 GSM)' }, stylingNotes: { en: 'Fitted tailored drape paired with pleat charcoal trousers and vintage signet rings.', ar: 'قصة انسيابية أنيقة مع بنطال قماشي رمادي ذو كسرات مع خواتم أثرية عتيقة.' }, sizeWorn: 'M', productId: 'hoodie-01', region: 'cairo', visible: true },
          { id: 'look-dubai-alserkal', image: { assetId: 'asset-editorial-streetwear' }, location: { en: 'Alserkal Avenue Contemporary Hub', ar: 'حي السركال أفينيو للفنون' }, modelName: { en: 'Zaid A.', ar: 'زيد ع.' }, productName: { en: 'Drop 01 Heavyweight Hoodie (520 GSM)', ar: 'هودي الإصدار الأول فائق الثقل (520 GSM)' }, stylingNotes: { en: 'High-volume architectural streetwear silhouette layered with cropped nylon vest.', ar: 'قوام ستريت وير عريض مع سترة نايلون قصيرة لإبراز تباين الخامات.' }, sizeWorn: 'XXL', productId: 'hoodie-01', region: 'dubai', visible: true },
          { id: 'look-london-shoreditch', image: { assetId: 'asset-editorial-streetwear' }, location: { en: 'Shoreditch Redbrick Industrial', ar: 'شوردتش / الطوب الأحمر الصناعي' }, modelName: { en: 'Salma T.', ar: 'سلمى ط.' }, productName: { en: 'Drop 01 Heavyweight Hoodie (520 GSM)', ar: 'هودي الإصدار الأول فائق الثقل (520 GSM)' }, stylingNotes: { en: 'Clean minimalist drape highlighting the matte gold diacritic chest embroidery.', ar: 'قصة مينيمال أنيقة تبرز تطريز الصدر الذهبي المطفي بدقة متناهية.' }, sizeWorn: 'L', productId: 'hoodie-01', region: 'london', visible: true },
        ],
      },
    },
    {
      id: 'home-serial-verifier',
      type: 'serialVerifier',
      visible: true,
      style: { ...navySection(), textAlign: 'center' },
      content: {
        badge: { en: 'ARCHIVAL SERIAL VERIFIER', ar: 'التحقق الأرشيفي الرقمي' },
        title: { en: 'Certificate of Authenticity', ar: 'التحقق من أصالة القطعة وسجل الإنتاج' },
        description: { en: 'Every LΛHΛB piece is individually numbered (1 of 200) with a woven tamper-proof security identifier. Verify its provenance and weaving batch here.', ar: 'تحمل كل قطعة من لَهَب رمزاً تسلسلياً فريداً منقوشاً على بطاقة العنق، يثبت أصالتها ومصدر غزلها وتطريزها اليدوي في مصر.' },
        inputLabel: { en: 'Archive serial identifier', ar: 'الرمز التسلسلي الأرشيفي' },
        submitLabel: { en: 'VERIFY PIECE', ar: 'فحص الأصالة' },
        demoSerials: ['LHB-01-018/200', 'LHB-01-042/200', 'LHB-01-084/200'],
      },
    },
    {
      id: 'home-archival-vault',
      type: 'archivalVault',
      visible: true,
      style: { ...navySection(), textAlign: 'center' },
      content: {
        badge: { en: 'ARCHIVAL VAULT // DROP 02', ar: 'خزينة الأرشيف القادم' },
        title: { en: 'Drop 02: [REDACTED]', ar: 'الإصدار الثاني // [مخفي]' },
        description: { en: 'Classified early look at our upcoming dawn silhouette capsule. Unlock the blueprints with your VIP pass or register for early allocation privileges.', ar: 'معاينة سرية وحصرية للقطع المعمارية القادمة من علامة لَهَب. أدخل رمز VIP الخاص بك أو سجل بياناتك لفتح المخططات.' },
        pieces: [
          { id: 'vault-cargo-pant', name: { en: 'Architectural Tapered Cargo Pant', ar: 'بنطال كارجو معمارى مدبب فائق المتانة' }, details: { en: 'Articulated knee darts, 6 concealed flap pockets, matte brass cinch buckles.', ar: 'ثنيات ركبة مفصلية مع 6 جيوب مخفية وإبزيم نحاسي مطفي.' }, status: { en: 'PROTOTYPE APPROVED // 150 UNITS', ar: 'تم اعتماد العينة // ١٥٠ قطعة فقط' }, visible: true },
          { id: 'vault-heavy-short', name: { en: 'Raw-Edge French Terry Heavy Short', ar: 'شورت صوف فرنسي ثقيل بحواف خام' }, details: { en: 'Hand-distressed raw leg hem, deep side welts, extended flat cotton drawstrings.', ar: 'حواف أرجل خام منسولة يدوياً مع أربطة قطنية عريضة ممتدة.' }, status: { en: 'IN WEAVING // 120 UNITS', ar: 'قيد النسيج بالمحلة // ١٢٠ قطعة فقط' }, visible: true },
          { id: 'vault-ribbed-beanie', name: { en: 'Chunky Ribbed Beanie w/ Brass Ingot', ar: 'قبعة صوفية مضلعة مع سبيكة نحاسية' }, details: { en: 'Custom engraved mini-ingot riveted on cuff, heavyweight zero-itch yarn.', ar: 'سبيكة معدنية مصغرة منقوشة على الحافة، خيوط ناعمة خالية من الحكة.' }, status: { en: 'ATELIER FINISHING // 80 UNITS', ar: 'اللمسات النهائية // ٨٠ قطعة فقط' }, visible: true },
        ],
        allowPasscode: true,
        allowWaitlist: true,
      },
    },
    {
      id: 'home-faq',
      type: 'faq',
      visible: true,
      style: navySection(),
      content: {
        badge: { en: '04 // ARCHIVE INQUIRIES & DETAILS', ar: '04 // استفسارات الأرشيف والتفاصيل' },
        title: { en: 'FREQUENTLY ASKED QUESTIONS', ar: 'الأسئلة الشائعة والمعلومات' },
        subtitle: { en: 'Essential information regarding domestic courier dispatch, garment longevity, Egyptian craftsmanship, and sizing assurances.', ar: 'كل ما تحتاج معرفته عن خدمات التوصيل المحلي، العناية بالنسيج الفاخر، أصالة التصنيع المصري، وضمان المقاسات.' },
        items: [
          { id: 'faq-shipping', category: { en: 'SHIPPING & DISPATCH', ar: 'الشحن والتوصيل' }, question: { en: 'How fast is delivery and can I inspect the piece upon arrival?', ar: 'كم تستغرق مدة التوصيل، وهل يمكنني معاينة القطعة قبل الاستلام؟' }, answer: { en: 'All Drop 01 orders are dispatched via dedicated express courier across Cairo, Giza, Alexandria, and all Egyptian governorates within 24 to 48 hours. We operate with Cash on Delivery (COD) and explicitly welcome physical garment inspection prior to acceptance, ensuring you can verify the heavyweight fleece density and gold embroidery threadwork firsthand.', ar: 'يتم شحن جميع طلبات الإصدار الأول عبر مندوب شحن سريع وموثوق إلى القاهرة والجيزة والإسكندرية وجميع محافظات مصر خلال 24 إلى 48 ساعة. نوفر خدمة الدفع عند الاستلام (نقداً أو بالبطاقة) مع ميزة فحص ومعاينة القطعة وخامتها الفاخرة بالكامل قبل الدفع والاستلام لضمان ثقتك التامة.' }, visible: true },
          { id: 'faq-care', category: { en: 'GARMENT CARE & LONGEVITY', ar: 'العناية بالنسيج والغسيل' }, question: { en: 'What are the recommended washing and care instructions for 520 GSM fleece?', ar: 'ما هي تعليمات الغسيل المثالية للحفاظ على هودي 520 جرام والتي شيرت؟' }, answer: { en: 'To preserve the architectural form, deep night-navy reactive dye, and high-density matte gold embroidery: wash inside out on a gentle cold cycle (30°C max) with mild detergent. Do not tumble dry—lay flat to dry in shade to maintain the boxy drape. If ironing is needed, steam lightly on the reverse side; never iron directly over the embroidery or back flame calligraphy.', ar: 'للحفاظ على قوام القطعة المعماري، ولون الكحلي الليلي الغني، وخيوط التطريز الذهبي: يُفضل غسل القطعة مقلوبة بالماء البارد (30 درجة مئوية كحد أقصى) مع منظف معتدل. تجنب التجفيف الآلي، وانشر القطعة أفقياً في الظل للحفاظ على انسيابية القماش. في حال الكي، استخدم البخار من الداخل وتجنب ملامسة المكواة مباشرة لسطح التطريز أو الطباعة الخلفية.' }, visible: true },
          { id: 'faq-origin', category: { en: 'ORIGIN & CRAFTSMANSHIP', ar: 'الأصالة والتصنيع' }, question: { en: 'Where are LAHAB pieces designed, milled, and manufactured?', ar: 'أين يتم تصميم وتصنيع وحياكة قطع لَهَب؟' }, answer: { en: 'Every LAHAB piece is conceived and architecturally patterned in Cairo. Our garments are crafted from 100% premium long-staple Egyptian cotton, custom-knitted into high-density 520 GSM French Terry fleece and 290 GSM combed jersey in historic Egyptian textile mills. Precision multi-head embroidery and archival screenprinting are executed locally with master artisans.', ar: 'صُممت قطع لَهَب بهندسة معمارية متقنة في قلب القاهرة، وتُحاك بالكامل من القطن المصري طويل التيلة 100%، المغزول خصيصاً في مصانع النسيج المصرية العريقة لإنتاج فرينش تيري بوزن 520 جرام وجيرسي ممشط بوزن 290 جرام. يتم تنفيذ التطريز الدقيق عالي الكثافة بأيدي أمهر الحرفيين المحليين.' }, visible: true },
          { id: 'faq-sizing', category: { en: 'SIZING & EXCHANGES', ar: 'المقاسات والاستبدال' }, question: { en: 'How does the boxy drop-shoulder fit work, and can I exchange sizes?', ar: 'كيف تختار مقاسك للقصة العريضة، وما هي سياسة الاستبدال؟' }, answer: { en: 'LAHAB garments are engineered with an intentional boxy drop-shoulder silhouette featuring 4–6 cm of ease. We advise selecting your standard size for the intended relaxed streetwear drape, or sizing down one size for a more tailored profile. If you require a size swap, we offer a complimentary 14-day exchange on unworn pieces with security tags intact.', ar: 'تتميز جميع قطعنا بقصة عريضة بأكتاف ساقطة تمنحك إطلالة أزياء الشارع الراقية (أوفر سايز). ننصح باختيار مقاسك المعتاد للحصول على القصة العريضة الأصلية، أو اختيار مقاس أصغر بدرجة لإطلالة أكثر انضباطاً. نوفر استبدالاً سهلاً وسريعاً للمقاس خلال 14 يوماً من الاستلام بشرط بقاء البطاقات الأمنية على القطعة.' }, visible: true },
        ],
      },
    },
    {
      id: 'home-contact',
      type: 'contact',
      visible: true,
      style: { ...navySection(), contentWidth: 'wide', textAlign: 'center' },
      content: {
        badge: { en: 'ATELIER CONCIERGE & BESPOKE INQUIRIES', ar: 'أتيليه لَهَب — خدمة العملاء والطلبات الخاصة' },
        title: { en: 'CONNECT WITH THE ATELIER', ar: 'تواصل مع الأتيليه' },
        description: { en: 'Our atelier concierge is dedicated to assisting you with architectural drape sizing, custom bespoke gold monogramming, and express regional courier tracking.', ar: 'فريق أتيليه لَهَب متواجد لخدمتك مباشرة للإجابة على استفسارات المقاسات، طلبات التطريز الخاص بالخيوط الذهبية، أو متابعة التوصيل السريع.' },
        email: 'lahabfire@gmail.com',
        phoneDisplay: '+20 128 822 4920',
        whatsappNumber: '201288224920',
        responseTime: { en: 'Avg. Response: < 2 Hours', ar: 'الرد خلال ساعتين بحد أقصى' },
        inquiryCategories: [
          { id: 'contact-bespoke', value: 'bespoke', label: { en: 'Bespoke Monogram / Custom Tailoring', ar: 'تطريز ذهبي مخصص وتفصيل خاص' } },
          { id: 'contact-sizing', value: 'sizing', label: { en: 'Sizing & Drop-Shoulder Drape Advice', ar: 'استشارة المقاس والقصة المعمارية' } },
          { id: 'contact-order', value: 'order', label: { en: 'Order Status & Express Tracking', ar: 'متابعة الشحن وحالة الطلب' } },
          { id: 'contact-drop-two', value: 'drop02', label: { en: 'Drop 02 VIP Allocation', ar: 'حجز مبكر للإصدار الثاني' } },
          { id: 'contact-press', value: 'press', label: { en: 'Press, Editorial & Partnerships', ar: 'الصحافة والتنسيق والتعاون' } },
          { id: 'contact-general', value: 'general', label: { en: 'General Atelier Inquiry', ar: 'استفسار عام' } },
        ],
      },
    },
    {
      id: 'home-footer',
      type: 'footer',
      visible: true,
      style: { ...navySection('xl'), background: { kind: 'theme', token: 'surfaceElevated' } },
      content: {
        brandDescription: { en: 'LAHAB. Contemporary streetwear forged in calligraphic heritage, nocturnal geometry, and heavyweight textile discipline.', ar: 'لَهَب. أزياء شارع معاصرة مصهورة في هندسة الخط، ألوان الليل الهادئة، وانضباط النسيج الثقيل.' },
        navigationHeading: { en: 'NAVIGATION', ar: 'التنقل في الموقع' },
        links: [
          { id: 'footer-top-link', label: { en: 'TOP // INTRO', ar: 'البداية // المقدمة' }, action: { type: 'scrollToSection', sectionId: 'home-hero' } },
          { id: 'footer-concept-link', label: { en: 'CONCEPT & STORY', ar: 'المفهوم والقصة' }, action: { type: 'scrollToSection', sectionId: 'home-brand-story' } },
          { id: 'footer-products-link', label: { en: 'DROP 01 PIECES', ar: 'قطع الإصدار الأول' }, action: { type: 'scrollToSection', sectionId: 'home-products' } },
          { id: 'footer-size-link', label: { en: 'SIZING & FABRICS', ar: 'المقاسات والأقمشة' }, action: { type: 'openSizeGuide' } },
        ],
        notificationHeading: { en: 'DROP NOTIFICATIONS', ar: 'إشعارات الإصدارات' },
        notificationDescription: { en: 'Drop 01 is strictly limited. Enter your email for private drop access and archive keys.', ar: 'المجموعة الأولى محدودة الكمية تمامًا. سجّل بريدك الإلكتروني للحصول على رموز الدخول المبكر.' },
        emailPlaceholder: { en: 'ENTER YOUR EMAIL...', ar: 'أدخل بريدك الإلكتروني...' },
        joinLabel: { en: 'JOIN', ar: 'تسجيل' },
        joinedMessage: { en: 'YOU ARE REGISTERED FOR DROP 01 ARCHIVE ALERTS.', ar: 'تم تسجيلك بنجاح في قائمة الإشعارات المبكرة للإصدار.' },
        communityHeading: { en: 'COMMUNITY ARCHIVE', ar: 'أرشيف المجتمع' },
        copyright: { en: 'LAHAB. ALL RIGHTS RESERVED.', ar: 'لَهَب. جميع الحقوق محفوظة.' },
        edition: { en: 'EDITION 1.0', ar: 'الإصدار 1.0' },
      },
    },
  ],
};
